apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: mssql-orders-db
spec:
  serviceName: mssql-orders-db
  replicas: 1
  template:
    metadata:
      labels:
        app: mssql-orders-db
    spec:
      terminationGracePeriodSeconds: 1
      containers:
      - name: mssql-orders-db
        image: mcr.microsoft.com/mssql/server:2017-latest
        ports:
        - containerPort: 1433
        env:
        - name: ACCEPT_EULA
          value: 'Y'
        - name: MSSQL_SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mssql
              key: SA_PASSWORD
        volumeMounts:
        - name: mssqldb
          mountPath: /var/opt/mssql
      volumes:
      - name: mssqldb
        persistentVolumeClaim:
          claimName: mssql-orders-data
---
apiVersion: v1
kind: Service
metadata:
  name: mssql-orders-db
spec:
  selector:
    app: mssql-orders-db
  ports:
  - protocol: TCP
    port: 1433
    targetPort: 1433
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mssql-orders-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fok-deployment-orders
  labels:
    app: fok-orders
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fok-orders
  template:
    metadata:
      labels:
        app: fok-orders
    spec:
      containers:      
      - name: orderapi
        image: caretro/foodonkontainers:ordersapi_v2
        ports:
        - containerPort: 80
        env:
        - name: "ASPNETCORE_ENVIRONMENT"
          value: "Production"
      imagePullSecrets:
      - name: regcredcaretro
---
kind: Service
apiVersion: v1
metadata:
  labels:
    name: reti-lab-foodonkontainers-orders-api
  name: reti-lab-foodonkontainers-orders-api
spec:
  selector:
    app: fok-orders
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80


